name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare for build
      run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=. -DBUILD_TESTS=ON
    
    - name: Build
      run: cmake --build build

    - name: Install
      run: cmake --install build

    - name: Upload tests
      uses: actions/upload-artifact@v2
      with:
        path: build/tests/

    - name: Upload libs
      uses: actions/upload-artifact@v2
      with:
        path: build/lib/

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download tests
      uses: actions/download-artifact@v2
      with:
        path: build/tests/

    - name: Download libs
      uses: actions/download-artifact@v2
      with:
        path: build/lib/

    - name: Run tests
      run: |
        chmod -R +x build/lib
        cd build/tests 
        chmod +x UNIT_TESTS 
        ctest --verbose
