name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare for build
      run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=./install -DBUILD_TESTS=ON -DBOOST_BUILD_CPU_THREADS=16
    
    - name: Build
      run: cmake --build build -- -j 16

    - name: Install
      run: cmake --install build

    - name: Upload install
      uses: actions/upload-artifact@v2
      with:
        path: install/

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download install
        uses: actions/download-artifact@v2
        with:
          path: install/

      - name: List
        run: ls -lst install/**

      - name: Unit tests
        run: cd install && chmod +x ./bin/tests/UNIT_TESTS && ./bin/tests/UNIT_TESTS

