name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare for build
      run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=. -DBUILD_TESTS=ON -DBOOST_BUILD_CPU_THREADS=16
    
    - name: Build
      run: cmake --build build -- -j 16

    - name: Install
      run: cmake --install build

    - name: Upload artifacts
      uses: actions/upload-artifacts@v2
      with:
        path: |
          build/tests/UNIT_TESTS
          build/tests/CTestTestfile.cmake
          build/lib/*.so

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifacts@v2
        with:
          path: |
            build/tests/UNIT_TESTS
            build/tests/CTestTestfile.cmake
            build/lib/*.so

      - name: Unit tests
        run: ctest --output-on-failure --test-dir build/tests

